# Generated by Django 6.0.6 on 2026-07-08 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_driverprofile_jobs_created_count'),
        ('coverage', '0004_backfill_primary_service_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('job_date', models.DateField()),
                ('job_type', models.CharField(choices=[('load', 'Load'), ('unload', 'Unload'), ('packing', 'Packing'), ('internal', 'Internal')], max_length=20)),
                ('workers_needed', models.PositiveIntegerField(default=1)),
                ('pricing_model', models.CharField(choices=[('flat_rate', 'Flat rate per worker'), ('hourly', 'Hourly rate per worker')], max_length=20)),
                ('flat_rate_per_worker', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight_lbs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Approximate weight (lbs)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='coverage.county')),
                ('driver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.driverprofile')),
            ],
            options={
                'ordering': ['-job_date', '-created_at'],
            },
        ),
    ]
