# Generated by Django 6.0.6 on 2026-07-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_status_jobapplication_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('applied', 'Applied'), ('invited', 'Invited')], default='applied', max_length=20),
        ),
    ]
