# Generated by Django 6.0.6 on 2026-07-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_friendmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
