# Generated by Django 6.0.6 on 2026-07-12 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_message_application_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='needs_equipment_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='needs_loading_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='needs_packing_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='needs_unloading_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='JobRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professionalism', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('punctuality', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('moving_skill', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('loading_skill', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('unloading_skill', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('packing_skill', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('equipment_skill', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='jobs.jobapplication')),
            ],
        ),
    ]
