# Generated by Django 6.0.6 on 2026-07-15 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_skill_flags_and_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='related_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages', to='jobs.job'),
        ),
    ]
