# Generated by Django 6.0.6 on 2026-07-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driverprofile_jobs_created_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='jobs_completed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
