# Generated by Django 6.0.6 on 2026-07-09 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='accounts.driverprofile')),
                ('laborer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='accounts.laborerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('driver_profile', 'laborer_profile')},
            },
        ),
    ]
