# Generated by Django 6.0.6 on 2026-07-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='jobs_completed_count',
        ),
    ]
