# Generated by Django 6.0.6 on 2026-07-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_backfill_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborerprofile',
            name='has_dolly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborerprofile',
            name='has_drills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborerprofile',
            name='has_floor_dolly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborerprofile',
            name='has_hump_straps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborerprofile',
            name='has_shoulder_dollies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborerprofile',
            name='has_tools',
            field=models.BooleanField(default=False),
        ),
    ]
