# Generated by Django 6.0.6 on 2026-07-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_tour',
            field=models.BooleanField(default=False),
        ),
    ]
