# Generated by Django 6.0.6 on 2026-07-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_has_seen_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_browse_jobs_tour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_seen_friends_tour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_seen_service_area_tour',
            field=models.BooleanField(default=False),
        ),
    ]
